#!/usr/bin/env bash
mkdir -p ~/.config/nvim/plugin
mkdir -p ~/.config/nvim/after/plugin
mkdir -p ~/.config/nvim/lua

# link wholesale
for f in -exec $(find . -regex ".*\.vim$\|.*\.lua$"); do
    rm -rf "$HOME/.config/nvim/$f"
    ln -s "$HOME/dotfiles/awesome-streamerrc/ThePrimeagen/$f" "$HOME/.config/nvim/$f"
done

